openapi: 3.0.0
info:
  title: MeusFilmes API
  version: 1.0.0
  description: API for the MeusFilmes application, providing access to movie data, user lists, and watched history.
servers:
  - url: /api
    description: Main API access via Nginx proxy

paths:
  # Health Check
  /health:
    $ref: './docs/health.yaml#/health_check'
  
  # Authentication Routes
  /auth/register:
    $ref: './docs/auth.yaml#/register'
  /auth/login:
    $ref: './docs/auth.yaml#/login'
  /auth/recovery:
    $ref: './docs/auth.yaml#/recovery'
  
  # Watched Movies Routes
  /movie/watched/:
    $ref: './docs/watched.yaml#/watched_movies'
  /movie/watched/{tmdb_id}:
    $ref: './docs/watched.yaml#/watched_movie_by_id'
  /movie/watched/count:
    $ref: './docs/watched.yaml#/watched_count'
  
  # Lists Routes
  /lists/:
    $ref: './docs/lists.yaml#/lists'
  /lists/add_movie:
    $ref: './docs/lists.yaml#/add_movie_to_list'
  /lists/{list_id}:
    $ref: './docs/lists.yaml#/list_by_id'
  /lists/{list_id}/movies/{tmdb_id}:
    $ref: './docs/lists.yaml#/remove_movie_from_list'
  /lists/public/{list_id}:
    $ref: './docs/lists.yaml#/public_list'
  
  # TMDB Routes
  /tmdb/config:
    $ref: './docs/tmdb.yaml#/config'
  /tmdb/popular:
    $ref: './docs/tmdb.yaml#/popular'
  /tmdb/movie/{tmdb_id}:
    $ref: './docs/tmdb.yaml#/movie_details'
  /tmdb/search:
    $ref: './docs/tmdb.yaml#/search'
  /tmdb/movie/{tmdb_id}/credits:
    $ref: './docs/tmdb.yaml#/credits'
  /tmdb/movie/{tmdb_id}/recommendations:
    $ref: './docs/tmdb.yaml#/recommendations'
  /tmdb/genres:
    $ref: './docs/tmdb.yaml#/genres_legacy'
  /tmdb/movie/genres:
    $ref: './docs/tmdb.yaml#/genres'
  /tmdb/discover/movie:
    $ref: './docs/tmdb.yaml#/discover'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    $ref: './docs/schemas.yaml#/components/schemas'

security:
  - bearerAuth: []
